services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - exchange1
      - exchange2
      - exchange3
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: redis
    env_file:
      - .env
    ports:
      - "6379:6379"

  exchange1:
    image: terow/exchanges:v1
    container_name: exchange1
    ports:
      - "40101:40101"

  exchange2:
    image: terow/exchanges:v2
    container_name: exchange2
    ports:
      - "40102:40102"

  exchange3:
    image: terow/exchanges:v3
    container_name: exchange3
    ports:
      - "40103:40103"

volumes:
  pgdata:
